class ImageRes {
  ImageRes._();

  static const String _imagePath = "assets/images/";
  static const String _iconPath = "assets/icons/";
  static const String banner1 = "${_imagePath}banner1.png";
  static const String banner2 = "${_imagePath}banner2.png";
  static const String banner3 = "${_imagePath}banner3.png";
  static const String userImage = "${_imagePath}admin.jpg";
  static const String labReport = "${_imagePath}report.png";
  static const String searchIcon = "${_iconPath}search.svg";
  static const String findDoner = "${_iconPath}find_doners.svg";
  static const String donate = "${_iconPath}donate.svg";
  static const String orderBlood = "${_iconPath}order.svg";
  static const String assistant = "${_iconPath}ai assistant.svg";
  static const String report = "${_iconPath}report.svg";
  static const String campaign = "${_iconPath}campaign.svg";
  static const String bloodDrop = "${_iconPath}Blood Drop.svg";
  static const String spike = "${_iconPath}spike.svg";
  static const String profile = "${_iconPath}profile.svg";
  static const String bloodBPlus = "${_iconPath}Blood Group.svg";
  static const String mapIcon = "${_iconPath}map-pin.svg";
  static const String bloodAPlus = "${_iconPath}A+.svg";
  static const String bloodABPlus = "${_iconPath}AB+.svg";
  static const String bloodOPlus = "${_iconPath}O+.svg";
  static const String bloodAMinus = "${_iconPath}A-.svg";
  static const String bloodABMinus = "${_iconPath}AB-.svg";
  static const String bloodOMinus = "${_iconPath}O-.svg";
  static const String bloodBMinus = "${_iconPath}B-.png";
  static const String homeIcon = "${_iconPath}home.svg";
  // static const String drop="${_iconPath}drop.png";
  static const String callIcon = "${_iconPath}call.png";
  static const String callNow = "${_iconPath}call_now.svg";
  static const String requestIcon = "${_iconPath}share.png";
  static const String request = "${_iconPath}Request.svg";
  static const String logout = "${_iconPath}logout.svg";
  static const String message = "${_iconPath}message.svg";
  static const String help = "${_iconPath}help.svg";
  static const String calendar = "${_iconPath}calender.svg";
  static const String drop = "${_iconPath}bdroop.svg";
}
